name: commons_tools_sdk
description: Pacote com helpers que facilitam em algumas funções das aplicações e SDKs.
version: 1.1.0
homepage: https://github.com/PhillipiLino/flutter-commons-tools-sdk

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^1.1.0
  intl: ^0.18.0
  shared_preferences: ^2.0.6
  equatable: ^2.0.3
  launchdarkly_flutter_client_sdk: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0