name: solfacil_tools_sdk
description: Pacote com helpers que facilitam em algumas funções das aplicações e SDKs.
version: 2.1.0
homepage: https://github.com/solfacil/cp.mt.sdk-tools-mobile

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.20.0
  firebase_analytics: ^9.2.1
  firebase_crashlytics: ^2.8.6
  cloud_firestore: ^3.4.0
  logger: ^1.1.0
  intl: ^0.17.0
  shared_preferences: ^2.0.6
  equatable: ^2.0.3
  launchdarkly_flutter_client_sdk: ^1.1.4
  mixpanel_flutter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0